[package]
name = "goober_eats"
version = "0.1.0"
authors = ["Spencer Gouw <59306451+rabirabirara@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ordered-float = "2.0.0"
fastrand = "1.3.3"
